### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Alan-FGR** [Alan-FGR/AtomicBot#1]
- [ ] revamp code to be OO and sane
- [ ] get rid of fuzzy matching, commands start with char (maybe `!`)
- [ ] save messages to server db in real time
- [ ] provide webpage to search in db
- [ ] store shared links, allow trusted users to easily include links in db with simple command, and add description (!savethatlink some description for link)
- [ ] provide webpage showing the links
- [ ] investigate [streams locking](https://gitter.im/nem0/LumixEngine?at=59e965b25c40c1ba79c26930)
- [ ] add bot webpage link on topic
- [ ] phase out shitty JS search thing?
- [ ]
